# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.WindowsTerminal.Preview
PackageVersion: 1.18.1421.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallModes:
- silent
PackageFamilyName: Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: x86
  InstallerType: msix
  InstallerUrl: https://github.com/microsoft/terminal/releases/download/v1.18.1421.0/Microsoft.WindowsTerminalPreview_1.18.1421.0_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 08F749E71FDEDBF967AED18163005727B4CD91BDBFC93847F4172CD18F3AC417
  SignatureSha256: 582B1B08A336D365A98DD27DC4031B9BB9AE2AAED2F200FDE25DB8CEA51CF8A8
  PackageFamilyName: Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://github.com/microsoft/terminal/releases/download/v1.18.1421.0/Microsoft.WindowsTerminalPreview_1.18.1421.0_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 08F749E71FDEDBF967AED18163005727B4CD91BDBFC93847F4172CD18F3AC417
  SignatureSha256: 582B1B08A336D365A98DD27DC4031B9BB9AE2AAED2F200FDE25DB8CEA51CF8A8
  PackageFamilyName: Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://github.com/microsoft/terminal/releases/download/v1.18.1421.0/Microsoft.WindowsTerminalPreview_1.18.1421.0_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 08F749E71FDEDBF967AED18163005727B4CD91BDBFC93847F4172CD18F3AC417
  SignatureSha256: 582B1B08A336D365A98DD27DC4031B9BB9AE2AAED2F200FDE25DB8CEA51CF8A8
  PackageFamilyName: Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe
ManifestType: installer
ManifestVersion: 1.4.0
