# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.PowerToys
PackageVersion: 0.90.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17134.0
InstallerType: burn
InstallerSwitches:
  Silent: /quiet /norestart
  SilentWithProgress: /quiet /norestart
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/microsoft/PowerToys/releases/download/v0.90.0/PowerToysUserSetup-0.90.0-x64.exe
  InstallerSha256: 2A6036F5B2D454084E55816C306E1E57EF1D14C916691CBDA42B469797605CE0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/microsoft/PowerToys/releases/download/v0.90.0/PowerToysSetup-0.90.0-x64.exe
  InstallerSha256: 12801C44F43D0CC61E90DF1EFDC40E4F3C88341E0199D5B20791042D9B173DCF
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/microsoft/PowerToys/releases/download/v0.90.0/PowerToysUserSetup-0.90.0-arm64.exe
  InstallerSha256: AB2E4DC87A9D764BE897C5170E2890E174C89CA912A1916FA3AE1E427536EA4A
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/microsoft/PowerToys/releases/download/v0.90.0/PowerToysSetup-0.90.0-arm64.exe
  InstallerSha256: 2998007C8FCD7BD2770767C6502AAA2CC75B85EC30DE62986EC7005EB0014EDB
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-03-31
